version: 0.2
    
phases:
  install:
    commands:
      - "./pants resolve.ivy"
  pre_build:
    commands:
      - "./pants buildgen"
      - git diff --exit-code || exit "$?"
  build:
    commands:
      - "./pants compile src:: test::"
      - "mkdir -p /mongod-testdata"
      - "mongod --dbpath /mongod-testdata &"
      - "./pants test test::"
  post_build:
    commands:
      - pkill mongod
