version: 0.2

env:
  variables:
    PANTS_CONFIG_OVERRIDE: "['pants.ini', 'pants-codebuild-ci.ini']"
  parameter-store: {}
    
phases:
  install:
    commands:
      - free -h
      - "./pants --jvm-run-jvm-options='' resolve.ivy"
  pre_build:
    commands:
      - "./pants buildgen"
      - git diff --exit-code || exit "$?"
  build:
    commands:
      - "./pants compile src:: test::"
      - "mkdir -p /mongod-testdata"
      - "mongod --dbpath /mongod-testdata &"
      - "./pants test test::"
  post_build:
    commands:
      - pkill mongod

cache:
  paths:
    - "/root/.cache/**/*"
    - ".pants.d/**/*"
    - ".local_artifact_cache/**/*"
